# Generated by Django 3.2.18 on 2023-04-23 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=180)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('date_started', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('websites_tried', models.IntegerField(default=0)),
                ('webcams_found', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=180)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.BooleanField(default=False)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('added_type', models.CharField(default='manual', max_length=10)),
                ('m3u8_address', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
    ]
