# Generated by Django 3.2.18 on 2023-04-22 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=180)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('date_started', models.DateField(blank=True, default=datetime.datetime(2023, 4, 22, 21, 12, 58, 264695))),
                ('status', models.BooleanField(default=False)),
                ('websites_tried', models.IntegerField(default=0)),
                ('webcams_found', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=180)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('status', models.BooleanField(default=False)),
                ('date_added', models.DateField(blank=True)),
                ('added_type', models.CharField(default='manual', max_length=10)),
                ('stream_url', models.CharField(max_length=180)),
            ],
        ),
    ]
