# Generated by Django 3.2.18 on 2023-04-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_webcam_webcam1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=180)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.BooleanField(default=False)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('added_type', models.CharField(default='manual', max_length=10)),
                ('m3u8_address', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Webcam1',
        ),
    ]
