version: '3.4'

services:

    reverse-proxy:
        image: nginx:1.17.10
        profiles: ["dev"]
        container_name: webcams-reverse_proxy
        depends_on: 
            - database
            - frontend
            - backend
            - crawl
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 80:80
        # logging:
        #   driver: none
      
    backend: 
        image: webcams/backend
        profiles: ["dev"]
        command: python manage.py runserver 0.0.0.0:8000
        container_name: webcams-backend
        depends_on:
            - database
        ports: 
            - 8000:8000
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: on-failure
        volumes:
            - ./backend:/code
   
    crawl: 
        image: webcams/crawl
        profiles: ["dev"]
        container_name: webcams-crawl
        environment:
            - CHROME_EXECUTABLE=${CHROME_EXECUTABLE}
        ports: 
            - 8080:8080
        restart: on-failure
        volumes:
            - ./crawl:/usr/src/app

    frontend: 
        image: webcams/frontend
        build: frontend
        profiles: ["dev"]
        container_name: webcams-frontend
        # depends_on:
            # - backend
        ports:
            - 9000:9000
        restart: on-failure
        volumes:
            - ./frontend/src:/app/src

    database:
        image: "postgres" 
        profiles: ["dev"]
        container_name: webcams-database
        ports:
            - 5432:5432
        volumes:
            - database:/var/lib/postgresql/data/
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        restart: on-failure
        # logging:
        #   driver: none

volumes:
    database:
