version: '3.4'

services:

    reverse-proxy:
        image: nginx:1.17.10
        profiles: ["dev"]
        container_name: reverse_proxy
        depends_on: 
            # - database
            - frontend
            # - backend
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 80:80
        logging:
          driver: none

    # backend: 
    #     image: webcams/backend
    #     profiles: ["dev", "backend"]
    #     container_name: backend
    #     depends_on:
    #         - database
    #     ports: 
    #         - 1337:1337
    #     restart: on-failure
    #     volumes:
    #         - ./backend/api:/app/api

    frontend: 
        image: webcams/frontend
        profiles: ["dev"]
        container_name: frontend
        entrypoint: [ "yarn", "dev" ]
        # depends_on:
            # - backend
        ports:
            - 9000:9000
        restart: on-failure
        volumes:
            - ./frontend/src:/app/src

    # database:
    #     image: "postgres" 
    #     profiles: ["dev", "backend"]
    #     container_name: database
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - database-data:/var/lib/postgresql/data/
    #     restart: on-failure
    #     logging:
    #       driver: none

# volumes:
#     database-data:
